import { useState } from 'react';
type F = [string, boolean, string];
const SHORT = ['bit.ly', 'tinyurl.com', 't.co', 'goo.gl', 'ow.ly', 'is.gd', 'buff.ly', 'rb.gy', 'cutt.ly'];
const BR = ['paypal', 'google', 'microsoft', 'apple', 'amazon', 'facebook', 'instagram', 'netflix', 'bank', 'whatsapp'];
const BADTLD = ['zip', 'mov', 'tk', 'top', 'xyz', 'click', 'gq', 'cf', 'ml', 'ga'];
const KEYW = ['login', 'verify', 'secure', 'update', 'account', 'password', 'confirm', 'wallet', 'invoice'];
const Note = () => <p className="msg">Indicative only: these local checks can never prove that a link, file, email or log is safe. Nothing is uploaded or opened, and no network request is made. Practice only in authorized environments.</p>;
const Res = ({ f }: { f: F[] }) => { const n = f.filter(x => x[1]).length; return (<div className="card" aria-live="polite" style={{ marginTop: 12 }}><h3>{n === 0 ? 'No obvious red flags' : n < 3 ? 'Suspicious: verify before trusting' : 'High risk: many red flags'} ({n} of {f.length} checks flagged)</h3><ul>{f.map(x => <li key={x[0]}>{x[1] ? '⚠ FLAG: ' : '✓ OK: '}<b>{x[0]}</b>{x[1] && x[2] ? <><br /><small>{x[2]}</small></> : null}</li>)}</ul></div>); };
function urlChecks(raw: string): { host: string; reg: string; f: F[] } | null {
  const full = raw.trim(); let u: URL; try { u = new URL(/^[a-z]+:\/\//i.test(full) ? full : 'http://' + full); } catch { return null; }
  const h = u.hostname.toLowerCase(); const lb = h.split('.'); const reg = lb.slice(-2).join('.'); const tld = lb[lb.length - 1];
  return { host: h, reg, f: [['Not encrypted (http)', u.protocol === 'http:', 'The page and anything you type travel unencrypted.'], ['Host is an IP address', /^\d{1,3}(\.\d{1,3}){3}$/.test(h) || h.startsWith('['), 'Real brands almost always use names.'], ['Contains user info before the host (@)', u.username !== '', 'Text before @ is ignored by the browser and can fake a trusted name.'], ['Punycode or non-ASCII host', h.includes('xn--') || /[^\x00-\x7f]/.test(full), 'Lookalike characters can imitate a real domain (homograph attack).'], ['Many subdomains', lb.length > 4, 'Long chains can hide the real domain on the right.'], ['Very long URL', full.length > 100, 'Length can hide the destination or carry encoded data.'], ['Known URL shortener', SHORT.includes(h), 'The destination is hidden. Preview it before opening.'], ['Brand name outside the real domain', BR.some(b => h.includes(b) && !reg.includes(b)), `The registrable domain (${reg}, approximate) matters, not words on the left.`], ['Often-abused top-level domain', BADTLD.includes(tld), 'Not proof, but common in throwaway campaigns.'], ['Many hyphens or digit-for-letter tricks', (h.match(/-/g) || []).length >= 3 || /[a-z]\d[a-z]/.test(lb[0] || ''), 'Examples: paypa1, secure-login-update.'], ['Unusual port', u.port !== '' && !['80', '443'].includes(u.port), 'Phishing kits and test servers often use odd ports.'], ['Urgent or credential words', KEYW.some(k => (h + u.pathname).toLowerCase().includes(k)), 'Common in phishing, and also in real sites.']] };
}
function Link() {
  const [v, setV] = useState('http://paypal.com.secure-login.example.net/verify?id=1'); const r = v.trim() ? urlChecks(v) : null;
  return (<><label htmlFor="ul">Paste a link (it is analyzed as text and never opened)</label><input id="ul" type="text" value={v} onChange={e => setV(e.target.value)} /><div className="row"><button onClick={() => setV('http://paypal.com.secure-login.example.net/verify?id=1')}>Suspicious example</button><button onClick={() => setV('https://www.wikipedia.org/')}>Normal example</button></div>
    {r ? <><p className="mono">Host: {r.host} · approximate real domain: {r.reg}</p><Res f={r.f} /></> : v.trim() ? <p className="msg">That does not look like a valid URL.</p> : null}</>);
}
const MG: [string, string, string[]][] = [['4d5a', 'Windows executable (PE)', ['exe', 'dll', 'sys', 'scr']], ['7f454c46', 'Linux executable (ELF)', ['', 'so', 'elf', 'bin']], ['25504446', 'PDF document', ['pdf']], ['504b0304', 'ZIP-based file (zip, Office, jar, apk)', ['zip', 'docx', 'xlsx', 'pptx', 'jar', 'apk', 'odt', 'docm', 'xlsm', 'pptm']], ['d0cf11e0', 'Legacy Office or installer (OLE)', ['doc', 'xls', 'ppt', 'msi']], ['89504e47', 'PNG image', ['png']], ['ffd8ff', 'JPEG image', ['jpg', 'jpeg']], ['47494638', 'GIF image', ['gif']], ['1f8b', 'gzip archive', ['gz', 'tgz']], ['52617221', 'RAR archive', ['rar']], ['377abcaf271c', '7-Zip archive', ['7z']], ['2321', 'Script with a shebang (#!)', ['sh', 'py', 'pl', 'rb', '']]];
const RISKY = ['exe', 'scr', 'bat', 'cmd', 'ps1', 'vbs', 'js', 'jse', 'wsf', 'hta', 'lnk', 'iso', 'img', 'jar', 'msi', 'dll', 'com', 'pif', 'reg'];
type FR = { name: string; size: number; type: string; sha: string; f: F[] };
async function inspect(file: File): Promise<FR> {
  const buf = await file.arrayBuffer(); const u8 = new Uint8Array(buf); const head = [...u8.slice(0, 8)].map(b => b.toString(16).padStart(2, '0')).join('');
  const sha = [...new Uint8Array(await crypto.subtle.digest('SHA-256', buf))].map(b => b.toString(16).padStart(2, '0')).join('');
  const s = u8.slice(0, 1048576); const cnt: number[] = new Array(256).fill(0); s.forEach(b => { cnt[b]++; }); const ent = s.length ? -cnt.reduce((a, c) => (c ? a + (c / s.length) * Math.log2(c / s.length) : a), 0) : 0;
  const parts = file.name.split('.'); const ext = (parts.length > 1 ? parts[parts.length - 1] : '').toLowerCase(); const m = MG.find(x => head.startsWith(x[0]));
  return { name: file.name, size: file.size, type: m ? m[1] : 'Unknown type', sha, f: [[`Risky extension (.${ext})`, RISKY.includes(ext), 'Can run code when opened.'], ['Double extension', /\.(pdf|docx?|xlsx?|jpe?g|png|txt)\.(exe|scr|bat|cmd|js|vbs|lnk|hta)$/i.test(file.name), 'Disguises a program as a document.'], ['Macro-enabled Office format', ['docm', 'xlsm', 'pptm'].includes(ext), 'Macros are a common malware delivery method.'], ['Content does not match the extension', !!m && !m[2].includes(ext), m ? 'The bytes look like: ' + m[1] + '.' : ''], ['Executable inside a harmless-looking name', !!m && /executable/.test(m[1]) && !RISKY.includes(ext), 'A program disguised as another file type.'], [`High entropy (${ent.toFixed(2)} bits per byte)`, ent > 7.5 && s.length > 51200, 'Compressed, encrypted or packed data. Normal for archives and media.'], ['Empty file', file.size === 0, '']] };
}
function FileTab() {
  const [r, setR] = useState<FR | null>(null); const [err, setErr] = useState(''); const [busy, setBusy] = useState(false);
  const pick = async (f?: File) => { setR(null); setErr(''); if (!f) return; if (f.size > 100e6) { setErr('File is larger than 100 MB. Choose a smaller one.'); return; } setBusy(true); try { setR(await inspect(f)); } catch { setErr('Could not read that file.'); } setBusy(false); };
  return (<><label htmlFor="uf">Choose a file (it is read in your browser and never uploaded)</label><input id="uf" type="file" onChange={e => { void pick(e.target.files?.[0]); }} />{busy && <p className="msg">Analyzing...</p>}{err && <p className="msg">{err}</p>}
    {r && <><div className="out"><div><b>Name</b>{r.name}</div><div><b>Size</b>{r.size.toLocaleString()} bytes</div><div><b>Detected from the first bytes</b>{r.type}</div><div><b>SHA-256</b>{r.sha}</div></div><Res f={r.f} />
      <p>Next step: look up the SHA-256 in a reputation service such as <a href="https://www.virustotal.com" target="_blank" rel="noopener noreferrer">VirusTotal</a> by pasting the hash. Do not upload private or confidential files to online scanners.</p></>}</>);
}
const dom = (s?: string) => (s?.match(/@([a-z0-9.-]+)/i)?.[1] || '').toLowerCase();
const SAMPLE_H = 'From: "PayPal Support" <service@paypa1-secure.example>\nReply-To: helpdesk@mail-collect.example\nReturn-Path: <bounce@bulkmailer.example>\nReceived: from mail.bulkmailer.example (203.0.113.45) by mx.corp.example; Tue, 07 Oct 2026 08:01:12 +0000\nReceived: from [10.0.0.5] (unknown) by mail.bulkmailer.example; Tue, 07 Oct 2026 08:01:10 +0000\nAuthentication-Results: mx.corp.example; spf=fail smtp.mailfrom=bulkmailer.example; dkim=none; dmarc=fail header.from=paypa1-secure.example\nSubject: Your account is limited\nDate: Tue, 07 Oct 2026 08:01:09 +0000';
function Mail() {
  const [t, setT] = useState(SAMPLE_H); const h: Record<string, string[]> = {};
  t.replace(/\r?\n[ \t]+/g, ' ').split(/\r?\n/).forEach(l => { const i = l.indexOf(':'); if (i > 0) { const k = l.slice(0, i).trim().toLowerCase(); h[k] = [...(h[k] || []), l.slice(i + 1).trim()]; } });
  const from = h['from']?.[0]; const auth = (h['authentication-results'] || []).join(' ').toLowerCase(); const get = (k: string) => auth.match(new RegExp(k + '=(\\w+)'))?.[1];
  const f: F[] = [['SPF did not pass (' + (get('spf') || 'not reported') + ')', get('spf') !== 'pass', 'The sending server is not authorized for the domain.'], ['DKIM did not pass (' + (get('dkim') || 'not reported') + ')', get('dkim') !== 'pass', 'The message is not signed, or the signature failed.'], ['DMARC did not pass (' + (get('dmarc') || 'not reported') + ')', get('dmarc') !== 'pass', 'The domain owner policy was not satisfied.'], ['Return-Path domain differs from From domain', !!h['return-path'] && dom(h['return-path'][0]) !== dom(from), 'Can be normal for mailing services, but also for spoofing.'], ['Reply-To domain differs from From domain', !!h['reply-to'] && dom(h['reply-to'][0]) !== dom(from), 'Replies would go somewhere you did not expect.'], ['Display name uses a brand but the domain does not match', BR.some(b => (from || '').split('<')[0].toLowerCase().includes(b) && !dom(from).includes(b)), 'Anyone can put any name in the display field.'], ['Missing Message-ID', !h['message-id'], 'Real mail servers normally add one.']];
  return (<><label htmlFor="mh">Paste the full email headers (a fictional sample is loaded)</label><textarea id="mh" rows={8} value={t} onChange={e => setT(e.target.value)} /><div className="row"><button onClick={() => setT(SAMPLE_H)}>Load sample</button></div>
    <Res f={f} /><div className="card" style={{ marginTop: 12 }}><h3>Delivery path (oldest first)</h3>{(h['received'] || []).slice().reverse().map((x, i) => <p className="mono" key={i}>{i + 1}. {x}</p>)}{!h['received'] && <p>No Received headers found.</p>}</div></>);
}
const SAMPLE_L = ['Oct 07 09:12:01 sshd: Failed password for admin from 203.0.113.45 port 51122', 'Oct 07 09:12:03 sshd: Failed password for root from 203.0.113.45 port 51124', 'Oct 07 09:12:05 sshd: Failed password for invalid user test from 203.0.113.45 port 51130', 'Oct 07 09:12:08 sshd: Failed password for ubuntu from 203.0.113.45 port 51134', 'Oct 07 09:12:11 sshd: Failed password for admin from 203.0.113.45 port 51140', 'Oct 07 09:12:15 sshd: Failed password for admin from 198.51.100.7 port 40022', 'Oct 07 09:14:02 sshd: Accepted password for admin from 203.0.113.45 port 51190', 'Oct 07 09:20:45 sshd: Accepted publickey for deploy from 192.0.2.25 port 40310'].join('\n');
function Logs() {
  const [t, setT] = useState(SAMPLE_L); const fail: Record<string, { n: number; u: Set<string> }> = {}; const ok: string[][] = [];
  t.split(/\r?\n/).forEach(l => { const a = l.match(/Failed password for (?:invalid user )?(\S+) from (\d+\.\d+\.\d+\.\d+)/); if (a) { const e = fail[a[2]] ?? (fail[a[2]] = { n: 0, u: new Set<string>() }); e.n++; e.u.add(a[1]); } const b = l.match(/Accepted \w+ for (\S+) from (\d+\.\d+\.\d+\.\d+)/); if (b) ok.push([b[1], b[2]]); });
  const rows = Object.entries(fail).map(([ip, e]) => ({ ip, n: e.n, u: [...e.u], ok: ok.filter(o => o[1] === ip).map(o => o[0]) })).sort((x, y) => y.n - x.n);
  return (<><label htmlFor="lg">Paste SSH authentication log lines (a fictional sample is loaded)</label><textarea id="lg" rows={8} value={t} onChange={e => setT(e.target.value)} /><div className="row"><button onClick={() => setT(SAMPLE_L)}>Load sample</button></div>
    <div className="tbl"><table><thead><tr><th>Source IP</th><th>Failed logins</th><th>Accounts tried</th><th>Verdict</th></tr></thead><tbody>{rows.map(r => <tr key={r.ip}><td className="mono">{r.ip}</td><td>{r.n}</td><td>{r.u.join(', ')}</td><td>{r.ok.length && r.n >= 3 ? `⚠ POSSIBLE COMPROMISE: success as ${r.ok.join(', ')} after failures` : r.n >= 5 ? '⚠ Possible brute force' : '✓ Low volume'}</td></tr>)}</tbody></table></div>
    {!rows.length && <p>No failed SSH logins found in the pasted text.</p>}<p>Rule of thumb used here: 5 or more failures from one address is a possible brute force, and a success from that address afterwards is treated as a possible compromise. Real detection also considers time windows, geography and baselines.</p></>);
}
export default function Analyze() {
  const [k, setK] = useState(0); const T = ['Link', 'File', 'Email headers', 'Auth logs'];
  return (<><h2>Analyzers</h2><p className="lead">Four local tools used in everyday defense: check a link, inspect a file, read email headers and spot brute force in logs. They run entirely in your browser.</p><Note />
    <div className="row">{T.map((t, i) => <button key={t} aria-pressed={k === i} onClick={() => setK(i)}>{t}</button>)}</div>{[<Link key="l" />, <FileTab key="f" />, <Mail key="m" />, <Logs key="g" />][k]}</>);
}
