// [category, techniques to learn, [tool, what it does, url][]]
export const AR: [string, string, string[][]][] = [
  ['Recon and OSINT', 'Passive vs active recon, DNS and subdomain enumeration, Google dorking, banner grabbing, social media OSINT', [
    ['Nmap', 'Port and service scanner', 'https://nmap.org'], ['Shodan', 'Search engine for exposed devices', 'https://www.shodan.io'], ['theHarvester', 'Emails, hosts and names from public sources', 'https://github.com/laramies/theHarvester'], ['Amass', 'Attack surface and subdomain mapping', 'https://github.com/owasp-amass/amass'], ['Maltego', 'Link analysis for investigations', 'https://www.maltego.com']]],
  ['Network analysis', 'Packet analysis, TCP handshake and flags, DNS/HTTP/TLS inspection, subnetting, VLANs, IDS signatures', [
    ['Wireshark', 'Packet analyzer', 'https://www.wireshark.org'], ['tcpdump', 'Command-line packet capture', 'https://www.tcpdump.org'], ['Zeek', 'Network security monitor', 'https://zeek.org'], ['Suricata', 'IDS/IPS engine', 'https://suricata.io'], ['Ncat', 'Netcat for connections and relays', 'https://nmap.org/ncat/']]],
  ['Web security', 'OWASP Top 10, SQLi, XSS, CSRF, SSRF, IDOR, auth bypass, JWT and API testing, directory fuzzing', [
    ['Burp Suite', 'Intercepting proxy and scanner', 'https://portswigger.net/burp/communitydownload'], ['OWASP ZAP', 'Free web app scanner', 'https://www.zaproxy.org'], ['sqlmap', 'SQL injection testing', 'https://sqlmap.org'], ['ffuf', 'Fast web fuzzer', 'https://github.com/ffuf/ffuf'], ['Nikto', 'Web server scanner', 'https://github.com/sullo/nikto']]],
  ['Exploitation', 'Vulnerability research, reverse shells, privilege escalation (Linux and Windows), pivoting, persistence, living off the land', [
    ['Metasploit', 'Exploitation framework', 'https://www.metasploit.com'], ['Exploit-DB', 'Public exploit archive', 'https://www.exploit-db.com'], ['Impacket', 'Python network protocol toolkit', 'https://github.com/fortra/impacket'], ['PEASS-ng', 'LinPEAS/WinPEAS privesc checks', 'https://github.com/peass-ng/PEASS-ng'], ['Sliver', 'Open source C2 for red teams', 'https://github.com/BishopFox/sliver']]],
  ['Active Directory', 'Kerberoasting, AS-REP roasting, pass-the-hash, NTLM relay, ACL abuse, GPO review, and how defenders detect each', [
    ['BloodHound', 'Maps attack paths in AD', 'https://github.com/SpecterOps/BloodHound'], ['NetExec', 'Network and AD assessment', 'https://github.com/Pennyw0rth/NetExec'], ['Responder', 'LLMNR/NBT-NS poisoning demo', 'https://github.com/lgandx/Responder'], ['Rubeus', 'Kerberos abuse toolkit', 'https://github.com/GhostPack/Rubeus']]],
  ['Passwords and auth', 'Hash types, salting, wordlists and rules, brute force vs dictionary, password policy, MFA, credential stuffing defense', [
    ['Hashcat', 'GPU password recovery', 'https://hashcat.net'], ['John the Ripper', 'Classic password cracker', 'https://www.openwall.com/john/'], ['Hydra', 'Online login tester', 'https://github.com/vanhauser-thc/thc-hydra'], ['Have I Been Pwned', 'Breach exposure lookup', 'https://haveibeenpwned.com']]],
  ['Wireless and mobile', 'WPA2/WPA3 handshakes, evil twin and rogue AP detection, Android/iOS app testing, firmware basics', [
    ['Aircrack-ng', 'Wi-Fi auditing suite', 'https://www.aircrack-ng.org'], ['Kismet', 'Wireless detector and sniffer', 'https://www.kismetwireless.net'], ['MobSF', 'Mobile app security framework', 'https://mobsf.github.io/docs/'], ['Frida', 'Dynamic instrumentation toolkit', 'https://frida.re']]],
  ['Forensics and IR', 'Disk and memory forensics, timelines, chain of custody, triage collection, NIST incident response lifecycle', [
    ['Autopsy', 'Disk forensics platform', 'https://www.autopsy.com'], ['Volatility 3', 'Memory forensics', 'https://github.com/volatilityfoundation/volatility3'], ['Velociraptor', 'Endpoint triage and hunting', 'https://docs.velociraptor.app'], ['Eric Zimmerman tools', 'Windows artifact parsers', 'https://ericzimmerman.github.io']]],
  ['SOC and detection', 'Log correlation, alert triage, detection engineering, threat hunting, ATT&CK mapping, SOAR playbooks', [
    ['Splunk', 'SIEM and log search', 'https://www.splunk.com'], ['Elastic Security', 'SIEM and EDR on the Elastic stack', 'https://www.elastic.co/security'], ['Wazuh', 'Open source XDR and SIEM', 'https://wazuh.com'], ['Security Onion', 'Free SOC distro', 'https://securityonionsolutions.com'], ['Sigma rules', 'Generic detection rule format', 'https://github.com/SigmaHQ/sigma']]],
  ['Malware and reversing', 'Static vs dynamic analysis, sandboxing, strings and imports, unpacking, YARA rules, assembly basics', [
    ['Ghidra', 'NSA reverse engineering suite', 'https://ghidra-sre.org'], ['x64dbg', 'Windows debugger', 'https://x64dbg.com'], ['ANY.RUN', 'Interactive malware sandbox', 'https://any.run'], ['VirusTotal', 'Multi-engine file and URL scan', 'https://www.virustotal.com'], ['YARA', 'Pattern matching for malware', 'https://virustotal.github.io/yara/']]],
  ['Cloud and containers', 'IAM least privilege, storage misconfigurations, shared responsibility, CSPM, Kubernetes and container security, IaC scanning', [
    ['Prowler', 'AWS/Azure/GCP security checks', 'https://github.com/prowler-cloud/prowler'], ['ScoutSuite', 'Multi-cloud auditing', 'https://github.com/nccgroup/ScoutSuite'], ['CloudGoat', 'Vulnerable-by-design AWS lab', 'https://github.com/RhinoSecurityLabs/cloudgoat'], ['Trivy', 'Container and IaC scanner', 'https://trivy.dev']]],
  ['AppSec and DevSecOps', 'Secure SDLC, SAST/DAST/SCA, threat modeling (STRIDE), secrets management, code review, CI/CD hardening', [
    ['Semgrep', 'Fast static code analysis', 'https://semgrep.dev'], ['SonarQube', 'Code quality and security', 'https://www.sonarsource.com/products/sonarqube/'], ['Dependency-Check', 'Vulnerable library finder', 'https://owasp.org/www-project-dependency-check/'], ['Gitleaks', 'Finds secrets in repos', 'https://github.com/gitleaks/gitleaks']]],
  ['Cryptography', 'AES/RSA/ECC, TLS configuration, certificate chains, hashing and HMAC, key management, common crypto mistakes', [
    ['CyberChef', 'Encode, decode and analyze data', 'https://gchq.github.io/CyberChef/'], ['OpenSSL', 'TLS and crypto toolkit', 'https://www.openssl.org'], ['GnuPG', 'PGP encryption and signing', 'https://gnupg.org'], ['testssl.sh', 'TLS configuration tester', 'https://testssl.sh']]],
  ['Systems and hardening', 'Least privilege, patching, auditd and Sysmon logging, firewalls (nftables), SSH hardening, security baselines', [
    ['Kali Linux', 'Security testing distro', 'https://www.kali.org'], ['Sysinternals', 'Windows deep-dive tools incl. Sysmon', 'https://learn.microsoft.com/sysinternals/'], ['Lynis', 'Linux security auditing', 'https://cisofy.com/lynis/'], ['CIS Benchmarks', 'Hardening guides', 'https://www.cisecurity.org/cis-benchmarks']]],
  ['Scripting and automation', 'Write scanners and log parsers, regex, calling APIs, automating repetitive tasks, version control, containers for labs', [
    ['Python', 'The security scripting language', 'https://www.python.org'], ['Bash', 'Shell scripting on Linux', 'https://www.gnu.org/software/bash/'], ['PowerShell', 'Windows automation', 'https://learn.microsoft.com/powershell/'], ['Git', 'Version control for your notes and tools', 'https://git-scm.com'], ['Docker', 'Disposable lab environments', 'https://www.docker.com']]],
  ['Intel, frameworks and GRC', 'IOC vs TTP, diamond model, pyramid of pain, STIX/TAXII, risk assessment, policies, audits, compliance mapping', [
    ['MITRE ATT&CK', 'Adversary tactics and techniques', 'https://attack.mitre.org'], ['MISP', 'Threat intel sharing platform', 'https://www.misp-project.org'], ['AlienVault OTX', 'Open threat exchange', 'https://otx.alienvault.com'], ['NIST CSF', 'Risk management framework', 'https://www.nist.gov/cyberframework'], ['CIS Controls', 'Prioritized defense actions', 'https://www.cisecurity.org/controls']]]];
