export type Item = { q: string; opts: string[]; pts: number[]; why: string[]; step?: string };
const yn = (ok: boolean, a: string, b: string, r: string): Pick<Item, 'opts' | 'pts' | 'why'> => ({ opts: [a, b], pts: ok ? [1, 0] : [0, 1], why: [(ok ? 'Correct. ' : 'Wrong. ') + r, (ok ? 'Wrong. ' : 'Correct. ') + r] });
const FW: [string, string, string, boolean, string][] = [
  ['10.0.0.15', '22', 'SSH', true, 'SSH is allowed from the internal 10.0.0.0/24 network.'], ['198.51.100.9', '443', 'HTTPS', true, 'Web traffic is open to everyone.'],
  ['203.0.113.45', '443', 'HTTPS', false, 'That IP is blocklisted, whatever the port.'], ['198.51.100.77', '22', 'SSH', false, 'SSH from outside the internal network is not allowed.'],
  ['192.0.2.8', '23', 'Telnet', false, 'Telnet is plaintext and not in the policy.'], ['10.0.0.22', '80', 'HTTP', true, 'Web is open to everyone.'],
  ['198.51.100.5', '3389', 'RDP', false, 'Exposed RDP is a top ransomware entry point.'], ['10.0.0.9', '445', 'SMB', false, 'Not in the policy, so default deny applies.'],
  ['192.0.2.50', '80', 'HTTP', true, 'Web is open to everyone.'], ['203.0.113.45', '80', 'HTTP', false, 'Blocklisted IP again.']];
export const FWI: Item[] = FW.map(f => ({ step: 'Policy: web (80, 443) open to all. SSH (22) only from 10.0.0.0/24. Block 203.0.113.45. Deny everything else.', q: `Source: ${f[0]}\nDestination port: ${f[1]} (${f[2]})`, ...yn(f[3], 'Allow', 'Block', f[4]) }));
const PH: [string, string, string, boolean, string][] = [
  ['billing@paypa1-support.com', 'Your account is limited', 'Verify within 24 hours or lose access:\nhttp://paypal.com.secure-login.example/verify', true, 'Lookalike sender (paypa1), urgency, and the real domain is secure-login.example.'],
  ['it@yourcompany.com', 'Maintenance Saturday 2am', 'Email will be unavailable for 30 minutes. No action needed.', false, 'Expected sender, no link, no pressure, no request for credentials.'],
  ['ceo@company-mail.co', 'Urgent task', 'I am in a meeting. Buy 5 gift cards and send me the codes. Do not call.', true, 'Business email compromise: authority, secrecy and an unusual payment request.'],
  ['noreply@github.com', 'New sign-in from Windows', 'If this was you, ignore this. Otherwise review security settings at github.com (type it yourself).', false, 'Informational, no pressure; you can verify by going to the site directly.'],
  ['hr@company.com', 'Salary update', 'Open the attached file now: Salaries_2026.pdf.exe', true, 'A double extension means it is really an executable.'],
  ['no-reply@microsft-365.com', 'Password expires today', 'Click here to keep your password.', true, 'Misspelled domain (microsft) plus urgency and a generic link.']];
export const PHI: Item[] = PH.map(p => ({ q: `From: ${p[0]}\nSubject: ${p[1]}\n\n${p[2]}`, ...yn(p[3], 'Phishing', 'Legitimate', p[4]) }));
export const IRI: Item[] = [
  { step: 'Phase 1: Detect and analyze', q: '02:07. Your EDR alerts: ransomware is encrypting files on a file server.', opts: ['Power off every server immediately', 'Isolate that host from the network but keep it powered on', 'Wait until morning'], pts: [1, 3, 0], why: ['Stops damage but destroys memory evidence and causes an outage.', 'Best: contains spread while preserving volatile evidence.', 'Every minute lets encryption spread.'] },
  { step: 'Phase 2: Contain', q: 'The host is isolated. Logs show a stolen admin account was used to get in.', opts: ['Disable the account, reset credentials, block the attacker IP', 'Reboot the server to see if it clears', 'Delete the encrypted files'], pts: [3, 0, 0], why: ['Best: removes attacker access across the environment.', 'Rebooting destroys evidence and fixes nothing.', 'Deleting makes recovery and forensics harder.'] },
  { step: 'Phase 3: Eradicate and recover', q: 'You need the file server back. Offline backups exist.', opts: ['Remove persistence, then restore from clean offline backups', 'Pay the ransom right away', 'Restore backups without finding the root cause'], pts: [3, 1, 1], why: ['Best: clean the system first, then restore.', 'No guarantee of recovery and it funds crime; involve legal and insurers.', 'The attacker will likely get back in the same way.'] },
  { step: 'Phase 4: Post-incident', q: 'Systems are back. What now?', opts: ['Write a report, fix the entry point, notify stakeholders and legal', 'Move on quietly', 'Blame the person who clicked'], pts: [3, 0, 0], why: ['Best: lessons learned and required notifications close the loop.', 'The same weakness will be exploited again.', 'Blame discourages reporting; fix process instead.'] }];
