const AC: string[][] = [['Cybercriminals', 'Money: ransomware, fraud, data theft and resale.', 'Phishing, credential stuffing, ransomware', 'MFA, tested backups, patching, awareness training'], ['Nation-state groups (APTs)', 'Espionage or disruption with patience and resources.', 'Supply chain compromise, zero-days, long-term persistence', 'Defense in depth, threat hunting, segmentation, rapid patching'], ['Hacktivists', 'Political or social causes.', 'DDoS, defacement, leaking data', 'DDoS protection, hardened web apps, monitoring'], ['Insiders', 'Staff or partners who misuse legitimate access.', 'Data copying, sabotage, careless sharing', 'Least privilege, logging, clean off-boarding'], ['Opportunists', 'Automated scanning for easy targets.', 'Known exploits and default passwords', 'Fast updates, no default credentials, minimal exposure']];
const TA: string[][] = [['Initial Access', 'MFA, email filtering, patching exposed services'], ['Execution', 'Application control, script logging, EDR'], ['Persistence', 'Monitor startup items, scheduled tasks and new accounts'], ['Privilege Escalation', 'Least privilege, patching, restricted sudo and admin rights'], ['Defense Evasion', 'Tamper protection, command-line logging, behavior-based EDR'], ['Credential Access', 'MFA, credential guard, unique passwords, monitoring logins'], ['Discovery', 'Honeytokens, alerts on unusual enumeration'], ['Lateral Movement', 'Segmentation, disable unused protocols, restrict admin shares'], ['Collection', 'Data classification, DLP, access logging'], ['Command and Control', 'Egress filtering, DNS monitoring, proxy logs'], ['Exfiltration', 'DLP, outbound traffic baselines, alerts on large transfers'], ['Impact', 'Offline backups, incident response plan, recovery testing']];
const CV: string[][] = [['CVE-2014-0160', 'Heartbleed', 'An OpenSSL bug let attackers read server memory.', 'Patch shared libraries fast and rotate keys after exposure.'], ['CVE-2014-6271', 'Shellshock', 'A Bash bug let crafted environment variables run commands.', 'Inputs reach surprising places: update shells and sanitize.'], ['CVE-2017-0144', 'EternalBlue (MS17-010)', 'A Windows SMBv1 flaw used by WannaCry.', 'Patch, disable SMBv1 and segment networks.'], ['CVE-2021-44228', 'Log4Shell', 'A logging library could load remote code from log text. CVSS 10.0.', 'Know your dependencies (SBOM) and update quickly.'], ['CVE-2021-34527', 'PrintNightmare', 'A Windows Print Spooler flaw allowed code execution.', 'Disable services you do not need, such as print spooler on servers.'], ['CVE-2022-0847', 'Dirty Pipe', 'A Linux kernel bug let unprivileged users overwrite read-only files.', 'Keep kernels patched and limit local access.']];
const TL: string[][] = [['1971', 'Creeper', 'An experimental self-replicating program moved between computers on ARPANET and displayed a message. It is often cited as the first computer worm.'], ['1988', 'The Morris worm', 'One of the first worms to spread widely across the early internet. It led to the creation of the first CERT Coordination Center.'], ['Late 1980s to 1990s', 'Firewalls arrive', 'Packet filters, and later stateful firewalls, became the standard way to separate networks.'], ['Mid 1990s', 'SSL and the encrypted web', 'Netscape introduced SSL, the ancestor of TLS, which made online shopping and banking practical.'], ['2000', 'ILOVEYOU', 'A worm spread by email showed how fast social engineering plus attachments can travel worldwide.'], ['2010', 'Stuxnet and Zero Trust', 'Stuxnet showed malware could damage physical industrial systems. The term "Zero Trust" was introduced by analyst John Kindervag.'], ['2014', 'Heartbleed', 'A flaw in OpenSSL showed how one open-source library can affect much of the internet.'], ['2017', 'WannaCry', 'Ransomware spreading through a Windows SMB flaw hit hospitals and companies, proving why patching and segmentation matter.'], ['2020 to 2021', 'Supply chain and Log4Shell', 'The SolarWinds compromise and the Log4Shell flaw put software supply chain security and SBOMs at the top of the agenda.'], ['2024', 'Post-quantum standards', 'NIST published its first post-quantum cryptography standards, including ML-KEM and ML-DSA.'], ['Today', 'AI on both sides', 'Defenders use machine learning for detection. Attackers use AI for convincing phishing and deepfakes, and LLM applications bring risks such as prompt injection.']];
export default function Intel() {
  return (<><h2>Threat intel and history</h2><p className="lead"><span className="tag">EDUCATIONAL DATA</span> General patterns and well-known historical cases for study. This is not a live feed and contains no real-time alerts.</p>
    <h3>Who attacks, and how to resist</h3><div className="grid">{AC.map(a => <div className="card" key={a[0]}><h3>{a[0]}</h3><p>{a[1]}</p><p><b>Typical techniques:</b> {a[2]}</p><p><b>Defenses:</b> {a[3]}</p></div>)}</div>
    <h3 style={{ marginTop: 32 }}>Attacker goals (MITRE ATT&amp;CK tactics) and defenses</h3><div className="tbl"><table><thead><tr><th>Tactic</th><th>Defensive ideas</th></tr></thead><tbody>{TA.map(t => <tr key={t[0]}><td><b>{t[0]}</b></td><td>{t[1]}</td></tr>)}</tbody></table></div>
    <h3 style={{ marginTop: 32 }}>Famous vulnerabilities to study</h3><p className="lead">Historical examples. For current details always check the <a href="https://nvd.nist.gov" target="_blank" rel="noopener noreferrer">NIST National Vulnerability Database</a>.</p>
    <div className="grid">{CV.map(c => <div className="card" key={c[0]}><span className="tag">{c[0]}</span><h3>{c[1]}</h3><p>{c[2]}</p><p><b>Lesson:</b> {c[3]}</p></div>)}</div>
    <h3 style={{ marginTop: 32 }}>Cybersecurity timeline</h3>{TL.map(t => <details className="tl" key={t[1]}><summary>{t[0]}: {t[1]}</summary><p>{t[2]}</p></details>)}</>);
}
