import { useState } from 'react';
import { useLS } from './hooks';
const SAFE: [string, string[][]][] = [
  ['Accounts and passwords', [['Use a password manager and a unique, long password or passphrase for every account', 'One leaked password then cannot open anything else.'], ['Turn on MFA everywhere, starting with email, banking and cloud storage', 'A stolen password alone is no longer enough.'], ['Prefer passkeys or an authenticator app over SMS codes', 'SMS can be hijacked by SIM swapping.'], ['Never read out a login code to anyone, even "support"', 'Codes are only ever for you. Scammers ask for them.'], ['Keep recovery options current and backup codes offline', 'You can recover without trusting a stranger.'], ['Check your email on haveibeenpwned.com and change affected passwords', 'Breaches are common. Knowing lets you react early.']]],
  ['Phishing and scams', [['Pause on urgency, fear or secrecy ("act now", "tell no one")', 'Pressure is the scammer main tool.'], ['Type the address yourself or use a bookmark instead of clicking email links', 'Lookalike domains fool the eye.'], ['Read the real domain from right to left, up to the first single slash', 'paypal.com.evil.example belongs to evil.example.'], ['Verify money or data requests through a second channel, such as a call to a known number', 'Defeats fake bosses, suppliers and relatives.'], ['Do not open unexpected attachments, and never "enable content" or macros', 'A very common malware delivery trick.'], ['Remember that voices, videos and caller ID can be faked', 'Deepfakes and spoofing are real.'], ['Report phishing to your IT team or mail provider, then delete it', 'It protects other people too.']]],
  ['Devices and software', [['Turn on automatic updates for the OS, browser, phone and apps', 'Most attacks use bugs that already have a fix.'], ['Replace devices and software that no longer get security updates', 'Unpatched systems are open doors.'], ['Use full-disk encryption (BitLocker, FileVault, LUKS) and a screen lock', 'Protects data if a device is lost or stolen.'], ['Use a standard account daily and an admin account only when needed', 'Limits what malware can do.'], ['Install software only from official stores or vendor sites', 'Cracked software often hides malware.'], ['Keep built-in protections on: firewall, Defender, Gatekeeper', 'Free and effective layers.']]],
  ['Home network and Wi-Fi', [['Change the default router admin password and keep its firmware updated', 'Default credentials are publicly known.'], ['Use WPA3 (or WPA2) with a long passphrase and turn off WPS', 'Weak Wi-Fi invites intruders.'], ['Put guests and smart-home gadgets on a separate guest network', 'A weak gadget then cannot reach your laptop.'], ['Avoid sensitive logins on public Wi-Fi, or use a trusted VPN', 'Open networks are easy to snoop on.'], ['Turn off remote administration of the router unless you need it', 'Less exposure to the internet.']]],
  ['Browsing and downloads', [['Keep the browser updated and remove extensions you do not use', 'Extensions can see everything you do.'], ['Never click through certificate warnings', 'They can signal interception.'], ['Download from the official site and check hashes or signatures when offered', 'Detects tampering.'], ['Be careful with QR codes and short links in public places', 'They can hide the real destination.']]],
  ['Backups and ransomware', [['Follow 3-2-1: three copies, two media types, one offline or offsite', 'Ransomware also encrypts connected backups.'], ['Test restoring a file every few months', 'An untested backup is a hope, not a plan.'], ['Block macros and risky attachments by default', 'A common ransomware entry point.'], ['Do not pay a ransom without expert advice, and report it', 'Payment gives no guarantee and funds crime.']]],
  ['Phones and mobile', [['Use a screen lock, biometrics and Find My Device, and keep the OS updated', 'Covers loss, theft and old bugs.'], ['Review app permissions and delete apps you do not use', 'Fewer apps, fewer leaks.'], ['Add a SIM PIN or a carrier port-out lock', 'Reduces SIM swap risk.'], ['Treat texts with links as suspicious (smishing)', 'Banks do not ask for codes by text.']]],
  ['Money and shopping', [['Use a separate or virtual card for online shopping and enable bank alerts', 'Limits and flags fraud quickly.'], ['Be skeptical of deals that are too good, and check the seller', 'Fake shops steal card details.'], ['Never pay a stranger with gift cards, crypto or wire transfers', 'Scammers prefer payments that cannot be reversed.'], ['Check statements monthly and use credit freezes where available', 'Spots misuse early.']]],
  ['Privacy and social media', [['Limit what you share publicly: birthday, address, workplace, travel plans', 'Attackers use it for guessing and pretexting.'], ['Set accounts to private and review connected apps', 'Removes stale access.'], ['Use separate email addresses or aliases for important accounts', 'Harder to link and target.'], ['Avoid posting photos of badges, tickets or documents', 'They are easy to misuse.']]],
  ['At work or in a business', [['Enforce MFA and least privilege, and remove access when people leave', 'Most breaches abuse access.'], ['Train staff on phishing and give them a simple way to report', 'People are the main target.'], ['Keep an inventory of devices and software and patch on a schedule', 'You cannot protect what you do not know.'], ['Write an incident plan with contacts, and practice it once', 'Speed matters during an incident.'], ['Check vendors and limit what they can reach', 'Supply chain attacks go through partners.']]],
  ['Physical and everyday', [['Lock your screen, shred sensitive paper and challenge tailgaters', 'Physical access bypasses technology.'], ['Do not plug in unknown USB sticks, and use your own charger in public', 'Malicious devices exist.']]]];
const TBL: string[][] = [['Phishing', 'Passkeys or MFA, checking the real domain, verifying requests, email filtering'], ['Credential stuffing', 'Unique passwords, MFA, breach monitoring'], ['Ransomware', 'Offline tested backups, patching, MFA, least privilege, segmentation'], ['Malware', 'Updates, official sources only, EDR or antivirus, no daily admin use'], ['Man-in-the-middle', 'HTTPS, VPN on untrusted networks, never ignoring certificate warnings'], ['SQL injection and XSS (site owners)', 'Parameterized queries, output encoding, CSP, WAF'], ['DDoS', 'CDN or scrubbing service, rate limiting, redundancy, response plan'], ['SIM swapping', 'Authenticator app or passkey, SIM PIN, carrier lock'], ['Social engineering and BEC', 'Callback verification, dual approval, training'], ['Insider threat', 'Least privilege, logging, clean off-boarding'], ['Supply chain attack', 'Vendor vetting, pinned and signed dependencies, SBOM, monitoring'], ['Evil twin Wi-Fi', 'WPA3, VPN, forgetting unknown networks, no auto-join'], ['Device theft', 'Disk encryption, screen lock, remote wipe'], ['Zero-day', 'Defense in depth, EDR, segmentation, fast patching'], ['Data breach at a service', 'Unique passwords, monitoring, credit freeze']];
const HACKED = ['Disconnect the affected device from the network, but do not wipe it yet if you may need evidence.', 'From a clean device, change passwords starting with your email, and turn on MFA.', 'Sign out all sessions and check recovery options and mail forwarding rules for changes.', 'Scan with a trusted security tool, or restore from a known clean backup.', 'If money or cards are involved, call your bank and consider a credit freeze.', 'Tell your IT or security team or provider, and report to the cybercrime authority in your country.', 'Warn your contacts if your account sent spam or scam messages.', 'Afterwards find out how it happened and fix that weakness.'];
export default function Safety() {
  const [c, setC] = useState('All'); const [done, setDone] = useLS<string[]>('sf', []);
  const total = SAFE.reduce((n, g) => n + g[1].length, 0); const tog = (k: string) => setDone(done.includes(k) ? done.filter(x => x !== k) : [...done, k]);
  return (<><h2>Stay safe: advice against every kind of attack</h2><p className="lead">No one can be 100% safe, but these habits stop the vast majority of real attacks. Tick the ones you have adopted. They are grouped by where you meet the risk.</p>
    <div className="mono">Habits adopted {done.length} / {total}</div><div className="bar"><i style={{ width: done.length / total * 100 + '%' }} /></div>
    <div className="row">{['All', ...SAFE.map(g => g[0])].map(x => <button key={x} aria-pressed={c === x} onClick={() => setC(x)}>{x}</button>)}</div>
    {SAFE.filter(g => c === 'All' || g[0] === c).map(g => <div key={g[0]}><h3 style={{ marginTop: 24 }}>{g[0]}</h3><div className="grid">{g[1].map(it => <div className="card" key={it[0]}><label className="chk"><input type="checkbox" checked={done.includes(it[0])} onChange={() => tog(it[0])} /><b>{it[0]}</b></label><p>{it[1]}</p></div>)}</div></div>)}
    <h3 style={{ marginTop: 32 }}>Attack type to best protection</h3><div className="tbl"><table><thead><tr><th>Attack</th><th>What helps most</th></tr></thead><tbody>{TBL.map(r => <tr key={r[0]}><td><b>{r[0]}</b></td><td>{r[1]}</td></tr>)}</tbody></table></div>
    <h3 style={{ marginTop: 32 }}>If you think you were hacked</h3><ol>{HACKED.map(h => <li key={h}>{h}</li>)}</ol></>);
}
