import { Fragment, useEffect, useState } from 'react';
const SC: { t: string; flow: string[]; notes: string[]; defend: string[]; h?: string }[] = [
  { t: 'Phishing', flow: ['Attacker', 'Fake website', 'Victim', 'Credential capture', 'Detection'], notes: ['The attacker prepares a convincing message and a lookalike site.', 'The fake site copies a real login page on a lookalike domain.', 'The victim clicks a link in a message that creates urgency.', 'Typed credentials go to the attacker. Some kits relay MFA codes too, but passkeys cannot be phished this way.', 'Defenders notice via reported emails, domain monitoring, impossible-travel logins and MFA alerts.'], defend: ['Passkeys or phishing-resistant MFA', 'Email filtering and link rewriting', 'Check the real domain', 'A report button and fast takedown'] },
  { t: 'SQL injection', flow: ['User input', 'Web application', 'Database', 'Response'], notes: ['A form field accepts text from a user.', 'If the app pastes that text into a SQL query, the input can change what the query means.', 'The database trusts the query and runs it, possibly returning or changing data it should not.', 'The response may leak data. Logs show unusual quotes or database errors.'], defend: ['Parameterized queries', 'Input validation', 'A least-privilege database account', 'Error messages that hide details, and a WAF'] },
  { t: 'DDoS', flow: ['Many sources', 'Internet', 'Target server', 'Overload'], notes: ['Thousands of compromised devices (a botnet) send traffic at the same time.', 'Traffic converges from many networks, so blocking one source does not help.', 'The target runs out of bandwidth, connections or CPU.', 'Real users cannot get through: an availability failure.'], defend: ['CDN and scrubbing service', 'Rate limiting', 'Autoscaling and redundancy', 'A response plan agreed with your provider'] },
  { t: 'Man-in-the-middle', flow: ['Client', 'Attacker', 'Server'], notes: ['The client tries to connect to the server.', 'On an untrusted network the attacker sits in the path, for example through a fake Wi-Fi hotspot.', 'Without encryption the attacker can read or change data. With TLS and certificate validation the browser warns you or the data stays unreadable.'], defend: ['HTTPS everywhere and HSTS', 'Certificate validation: never click through warnings', 'A VPN on untrusted networks', 'Avoiding unknown Wi-Fi'] },
  { t: 'XSS', flow: ['Attacker', 'Vulnerable page', 'Victim browser', 'Stolen session'], notes: ['The attacker finds a page that shows user-supplied text without encoding it.', 'They store or send a crafted script so the page includes it.', 'A victim opens the page and their browser runs the script as if the site wrote it.', 'The script can read what the page can, such as a session token if cookies are not protected.'], defend: ['Encode output for the right context', 'Content Security Policy', 'HttpOnly and SameSite cookies', 'Input validation as an extra layer'] },
  { t: 'Ransomware', flow: ['Phishing email', 'Initial access', 'Spread', 'Data theft', 'Encryption', 'Ransom note'], notes: ['A user receives a convincing email with a malicious attachment or link.', 'Code runs on one machine and the attacker gains a foothold.', 'They steal credentials and move to other machines and servers.', 'Data is copied out first, to add pressure with a leak threat.', 'Files are encrypted, often including connected backups.', 'A note demands payment. Recovery now depends on backups and the incident plan.'], defend: ['MFA and email filtering', 'Patching and least privilege', 'Network segmentation', 'Offline, tested backups', 'EDR with fast response'] },
  { t: 'Credential stuffing', flow: ['Leaked passwords', 'Automated logins', 'Reused password works', 'Account takeover'], notes: ['Passwords leaked from one breached site circulate among criminals.', 'Bots try those pairs on many other sites at high speed.', 'People who reuse passwords are let in without any hacking at all.', 'The attacker uses the account for fraud, theft or more phishing.'], defend: ['Unique passwords from a password manager', 'MFA or passkeys', 'Rate limiting and bot detection', 'Checking passwords against breach lists'] },
  { t: 'TLS handshake', h: 'What it gives you', flow: ['Client hello', 'Server hello and certificate', 'Verify certificate', 'Keys derived', 'Encrypted data'], notes: ['The browser lists the TLS versions and ciphers it supports and sends its half of a key exchange.', 'The server chooses the settings, sends its half of the key exchange and its certificate.', 'The browser checks the certificate chain, the site name and the expiry against trusted authorities.', 'Both sides compute the same session keys without ever sending them.', 'Data is encrypted with fast symmetric keys, fresh for every session.'], defend: ['Confidentiality: eavesdroppers see ciphertext', 'Authentication: the certificate proves the server', 'Integrity: tampering is detected', 'Forward secrecy: old traffic stays safe if a key leaks later'] },
  { t: 'Supply chain', flow: ['Attacker', 'Trusted vendor update', 'Your systems', 'Backdoor active'], notes: ['The attacker compromises a software vendor or an open-source dependency.', 'A malicious change ships inside a normal-looking update.', 'Your systems install it automatically because the source is trusted.', 'The attacker now has access inside many organizations at once.'], defend: ['Verify signatures and hashes', 'Pin and review dependency versions', 'Keep an SBOM and scan dependencies', 'Least privilege and egress controls'] }];
export default function Sims() {
  const [k, setK] = useState(0); const [i, setI] = useState(0); const [play, setPlay] = useState(false); const s = SC[k];
  useEffect(() => { if (!play) return; const t = setInterval(() => setI(x => (x + 1) % s.flow.length), 1800); return () => clearInterval(t); }, [play, s]);
  return (<><h2>Attack simulations</h2><p className="lead">Step through how common attacks work, then see what stops them. These are concept animations for learning, not attack tools.</p>
    <div className="row">{SC.map((x, n) => <button key={x.t} aria-pressed={k === n} onClick={() => { setK(n); setI(0); setPlay(false); }}>{x.t}</button>)}</div>
    <div className="fl" role="list">{s.flow.map((f, n) => <Fragment key={f}>{n > 0 && <i aria-hidden="true">→</i>}<b role="listitem" className={n <= i ? 'on' : ''} aria-current={n === i ? 'step' : undefined}>{f}</b></Fragment>)}</div>
    <div className="card" aria-live="polite"><span className="tag">Step {i + 1} of {s.flow.length}</span><p>{s.notes[i]}</p></div>
    <div className="row" style={{ marginTop: 12 }}><button onClick={() => setI(Math.max(0, i - 1))}>Back</button><button onClick={() => setI(Math.min(s.flow.length - 1, i + 1))}>Next</button><button onClick={() => setPlay(!play)}>{play ? 'Pause' : 'Auto-play'}</button></div>
    <h3 style={{ marginTop: 24 }}>{s.h || 'How defenders stop it'}</h3><div className="grid">{s.defend.map(d => <div className="card" key={d}><p>{d}</p></div>)}</div></>);
}
