// [display name|alias|alias, plain-English definition]. Used by the Glossary page and CyberBot.
export const KW: string[][] = [
  [`SQL injection|sqli`, `Tricking a database query with crafted input. Prevented with parameterized queries.`],
  [`XSS|cross-site scripting`, `Injecting script into a page other users view. Prevented with output encoding and a Content Security Policy.`],
  [`CSRF|cross-site request forgery`, `Making a logged-in user's browser send an unwanted request. Prevented with anti-CSRF tokens and SameSite cookies.`],
  [`SSRF|server-side request forgery`, `Making a server fetch URLs the attacker chooses, often to reach internal systems.`],
  [`XXE|xml external entity`, `Abusing XML parsers that load external files or URLs. Disable external entities.`],
  [`Path traversal|directory traversal`, `Using ../ in input to reach files outside the intended folder.`],
  [`Command injection`, `Input that ends up inside an operating system command. Avoid shells and validate input.`],
  [`Clickjacking`, `Hiding a page under a decoy so users click something they did not intend. Prevent with frame-ancestors.`],
  [`Session hijacking`, `Stealing or guessing a session token to act as the user.`],
  [`Brute force`, `Trying many passwords or keys until one works. Slowed by lockouts and rate limits.`],
  [`Credential stuffing`, `Trying leaked username and password pairs on other sites, because people reuse passwords.`],
  [`Password spraying`, `Trying a few common passwords against many accounts to avoid lockouts.`],
  [`Rainbow table`, `A precomputed table of hashes for cracking passwords. Defeated by salting.`],
  [`Spear phishing`, `Phishing aimed at one specific person, using personal details.`],
  [`Whaling`, `Phishing aimed at senior executives.`],
  [`Vishing`, `Phishing by voice call.`],
  [`Smishing`, `Phishing by text message.`],
  [`Trojan`, `Malware disguised as useful software.`],
  [`Worm`, `Malware that spreads by itself across networks.`],
  [`Virus`, `Malware that attaches to files and spreads when they are run.`],
  [`Rootkit`, `Malware that hides itself and other malware deep in the system.`],
  [`Keylogger`, `Software or hardware that records what you type.`],
  [`Botnet`, `A network of infected devices controlled remotely, used for DDoS and spam.`],
  [`Spyware`, `Software that secretly collects information about you.`],
  [`Backdoor`, `A hidden way into a system that bypasses normal login.`],
  [`RAT|remote access trojan`, `Malware that gives an attacker remote control of a computer.`],
  [`Watering hole`, `Compromising a website that the targets visit often.`],
  [`Drive-by download`, `Malware installed just by visiting a booby-trapped page.`],
  [`Typosquatting`, `Registering lookalike domains to catch typing mistakes.`],
  [`Malvertising`, `Malicious ads that spread malware.`],
  [`Cryptojacking`, `Secretly using someone else's computer to mine cryptocurrency.`],
  [`Logic bomb`, `Malicious code that triggers on a condition, such as a date.`],
  [`Deepfake`, `AI-generated fake audio, image or video, used for fraud and disinformation.`],
  [`APT|advanced persistent threat`, `A skilled, well-resourced attacker that stays in a network for a long time.`],
  [`Persistence`, `Ways an attacker keeps access after a reboot, such as scheduled tasks or startup entries.`],
  [`Data exfiltration|exfiltration`, `Secretly moving stolen data out of a network.`],
  [`Threat actor`, `The person or group behind an attack: criminals, hacktivists, nation states or insiders.`],
  [`Hacktivist`, `An attacker motivated by political or social causes.`],
  [`Script kiddie`, `An unskilled attacker who uses ready-made tools.`],
  [`White hat|ethical hacker`, `A hacker who tests systems with permission to help fix problems.`],
  [`Black hat`, `A hacker who attacks without permission for harm or profit.`],
  [`Grey hat`, `Hacks without permission but without malicious intent. Still often illegal.`],
  [`WAF|web application firewall`, `A firewall that filters web requests for attacks such as SQL injection.`],
  [`EDR|XDR|MDR`, `Endpoint, extended and managed detection and response: tools or services that watch devices and respond to threats.`],
  [`Antivirus`, `Software that detects known malware using signatures and behavior.`],
  [`Sandbox|sandboxing`, `An isolated environment for running suspicious files safely.`],
  [`Patch management`, `Tracking and installing software updates promptly.`],
  [`Vulnerability scanning`, `Automated checks that find known weaknesses in systems.`],
  [`Penetration testing|pentest|pen test|penetration`, `An authorized, simulated attack to find weaknesses, followed by a report.`],
  [`Red team`, `Authorized attackers who test an organization's defenses.`],
  [`Blue team`, `Defenders who monitor, detect and respond.`],
  [`SOC|security operations center`, `The team and place that monitors and responds to security events.`],
  [`CISO`, `Chief information security officer: the executive responsible for security.`],
  [`Air gap`, `Keeping a system physically disconnected from other networks.`],
  [`Bastion host|jump box`, `A hardened server used as the single entry point to administer other systems.`],
  [`Hardening`, `Reducing the attack surface by removing unneeded software and tightening settings.`],
  [`Baseline`, `The approved standard configuration, or normal behavior, to compare against.`],
  [`3-2-1 backup`, `Keep 3 copies on 2 types of media with 1 stored offsite or offline.`],
  [`IAM|identity and access management`, `Processes and tools that control who has access to what.`],
  [`Playbook|runbook`, `Step-by-step instructions for handling a specific incident or task.`],
  [`Incident response`, `The organized process of preparing for, detecting, containing and recovering from incidents.`],
  [`False positive`, `An alert for something harmless.`],
  [`False negative`, `A real attack that the tool missed.`],
  [`Attack surface`, `All the points where an attacker could try to get in.`],
  [`Security control`, `A safeguard that prevents, detects or corrects a risk: technical, administrative or physical.`],
  [`PKI|public key infrastructure`, `The system of certificates and authorities that makes public keys trustworthy.`],
  [`TLS|SSL`, `The protocol that encrypts web traffic (HTTPS). SSL is its obsolete predecessor.`],
  [`Digital certificate|x.509`, `A signed file that binds a public key to an identity, such as a website.`],
  [`Digital signature`, `A value made with a private key that proves who signed the data and that it was not altered.`],
  [`AES`, `The standard fast symmetric encryption algorithm, used with 128 or 256-bit keys.`],
  [`RSA`, `A widely used public-key algorithm for encryption and signatures.`],
  [`ECC|elliptic curve`, `Public-key cryptography that gets similar strength to RSA with smaller keys.`],
  [`SHA-256|sha2`, `A modern hash function that outputs 256 bits.`],
  [`HMAC`, `A hash combined with a secret key to check that a message came from the key holder, unaltered.`],
  [`bcrypt|argon2|scrypt`, `Slow password-hashing functions designed to make guessing expensive.`],
  [`Steganography`, `Hiding a message inside another file, such as an image.`],
  [`NIST`, `US standards body that publishes widely used guidance such as the Cybersecurity Framework.`],
  [`ISO 27001`, `The international standard for an information security management system.`],
  [`CIS Controls|cis benchmarks`, `Prioritized security actions and hardening guides from the Center for Internet Security.`],
  [`MITRE ATT&CK|mitre|attack framework`, `A knowledge base of real attacker tactics and techniques.`],
  [`OWASP`, `An open community that publishes free web security guidance, such as the OWASP Top 10.`],
  [`CWE`, `Common Weakness Enumeration: a catalog of types of software weaknesses.`],
  [`DREAD`, `An older threat-rating model: Damage, Reproducibility, Exploitability, Affected users, Discoverability.`],
  [`Diamond model`, `A way to analyze intrusions using adversary, capability, infrastructure and victim.`],
  [`Pyramid of pain`, `Shows that blocking file hashes is easy for attackers to dodge, while detecting behaviors (TTPs) hurts them most.`],
  [`Kill chain`, `The Lockheed Martin model of attack stages, from reconnaissance to actions on objectives.`],
  [`OSI model`, `Seven networking layers: physical, data link, network, transport, session, presentation, application.`],
  [`TCP`, `A reliable, ordered connection protocol that starts with a three-way handshake.`],
  [`UDP`, `A fast, connectionless protocol with no delivery guarantee, used for DNS and streaming.`],
  [`NAT`, `Translates private addresses to a public one so many devices can share it.`],
  [`VLAN`, `A virtual network on a switch that separates traffic logically.`],
  [`IPsec`, `A suite of protocols that encrypts and authenticates IP traffic, common in VPNs.`],
  [`WPA3|wpa2`, `Wi-Fi security standards. WPA3 is the newer, stronger one.`],
  [`DHCP`, `Automatically gives devices an IP address when they join a network.`],
  [`ICMP`, `The control protocol behind ping and network error messages.`],
  [`Proxy`, `A server that relays requests for clients, used for filtering and privacy.`],
  [`chmod`, `Linux command that changes file permissions, for example chmod 600 file.`],
  [`sudo`, `Runs one command with administrator (root) rights after you authenticate.`],
  [`systemd|systemctl`, `The service manager on most Linux systems. systemctl starts, stops and inspects services.`],
  [`journalctl`, `Command that reads the logs collected by systemd.`],
  [`SSH|secure shell`, `Encrypted remote login and file transfer protocol, normally on port 22.`]];
